url: "https://nasiijau.github.io/portfolio" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "nas" # the name of your site, e.g. ACME Corp.
